config/routes.rb
Rails.application.routes.draw do
  #our root is the vote index. As good a landing page as any!
  root 'votes#index'
  resources :votes, only: [:create, :index]
  resources :suggestions, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snack_api.rb
#i've rolled all our API interactions into its own model
#thus if the api ever changes all we have to do is modify this file
#remember to set up your api key as an env variable using figaro
#https://github.com/laserlemon/figaro


class SnackAPI
  #in case the url changes or there's a need to use a client other than 
  #httparty this makes life easier for testing purposes as well, letting us stub
  #out the requests, and reducing load on the actual api
  #api docs: https://api-snacks.nerderylabs.com/v1/help
  def initialize(client = HTTParty,  
                url = "https://api-snacks.nerderylabs.com/v1/snacks",
                key = ENV["APIkey"])

    @url = url
    @client = client
    #header requires the content type or else the post requests will fail
    #not technically needed for the get request but it doesn't adversely affect it
    @header =  {Authorization: "ApiKey #{key}",
                'Content-Type' => 'application/json'}
  end

  #a simple method to test if the API is working
  def online?
     response = @client.get(@url, 
                headers: @header
                )
     response.code == 200
  end


  def get_snacks
    @client.get(@url, 
                headers: @header
                )
  end

  def add_snack(snack, location)
    #this originally also had lattiude and longitude
    #but as its not used anywhere in the codebase 
    #i refactored away from it. YAGNI 
    @client.post(@url, 
                headers: @header,
                body: {
                  "name" => snack,
                  "location" => location
                  }.to_json)
  end

end

app/models/snack_data.rb
#class that gathers data from the snack API
class SnackData
  #client gets passed in so we can more easally stub
  #method simply gets all the snacks and returns those with "optional: false"
  def self.permanent_snacks(client=SnackAPI.new)
    snack_array = client.get_snacks
    mandatory_array = [] 
    snack_array.each do |snack|
      if !snack["optional"]
        mandatory_array << snack
      end
    end
    mandatory_array
  end 

  def self.optional_snacks(client=SnackAPI.new)
    snack_array = client.get_snacks
    optional_array = [] 
    snack_array.each do |snack|
      if snack["optional"]
        optional_array << snack
      end
    end
    optional_array
  end
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  validate :name_not_permanent
  validates :location, presence: true

  def name_not_permanent(sug = Suggestion)
    if name.present? && sug.permanent_names.include?(name)
      errors.add("That is a permanently stocked snack")
    end
  end


  def self.permanent_names(snackdata = SnackData)
    reduce_to_names(snackdata.permanent_snacks)
  end

  #this method gets the optional snacks and adds the current vote total to the ones that are still there.  
  def self.suggestion_data(snackdata = SnackData)
    add_votes(snackdata.optional_snacks) 
  end

  def self.unused_api_suggestions(snackdata = SnackData)
    api_snacks = reduce_to_names(snackdata.optional_snacks)
    suggestions = reduce_to_names(Suggestion.all)
    api_snacks - suggestions || suggestions - api_snacks
  end

  private 

  def self.reduce_to_names(arr)
    #this method takes an array of hashes returned and reduces it to an array of names
    new_arr = arr.map do |snack|
      snack = snack[:name] || snack["name"]
    end
    new_arr
  end

  def self.add_votes(arr)
    #this method takes the array of hashes returned by the API and turns it into a list of those which have been suggested this month, it also appends the number of votes to each hash.
    name_list = []
    arr.each do |item|
      unless self.where(name: item["name"]).empty? 
        item["votes"] = self.where(name: item["name"]).first.votes
        name_list << item
      end
    end
    name_list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  def index
    if cookies[:suggestions].blank?
      expiration = Time.parse(Date.today.end_of_month.to_s)
      cookies[:suggestions] = {value: 1, :expires => expiration}
    end
    @online = SnackAPI.new.online?
    @submissions_left = cookies[:suggestions].to_i
    @suggestions = Suggestion.unused_api_suggestions
  end

  def create
    #two cases need to be handled here, the dropdown, and the form, we also handle cookie logic
    #not as skinny as I would like for sure. 
    suggestion = Suggestion.new(name: create_params["snack_name"], location: create_params["location"], votes: 0)
    if cookies[:suggestions].to_i < 1
      flash[:danger] = "You are out of suggestions"
      redirect_back(fallback_location: 'suggestion#index')
      return
    end

    if suggestion.valid? && Suggestion.unused_api_suggestions.include?(create_params["snack_name"])

      cookies[:suggestions] = cookies[:suggestions].to_i - 1
      
      suggestion.save
      flash[:success] = "Suggested!"
      redirect_back(fallback_location: 'suggestion#index')
    elsif suggestion.valid?
      SnackAPI.new.add_snack(create_params["snack_name"], create_params["location"])
      
      cookies[:suggestions] = cookies[:suggestions].to_i - 1

      suggestion.save
      flash[:success] = "Suggested!"
      redirect_back(fallback_location: 'suggestion#index')
    else 
      flash[:danger] = error_message(suggestion)
      redirect_back(fallback_location: 'suggestion#index')
    end
  end

  def create_params
    params.require(:suggestion).permit(:snack_name, :location)
  end

  def error_message(suggestion)
    if suggestion.errors.include?(:location) 
      return "A location must be provided"
    else
      return "That snack has already been suggested!"
    end    
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  #write some tests for this controller
  #Write rake task to be run every month (via cron, to reset "selected") (will delete the suggestions table)
  #re-write readme

  def index
    if cookies[:votes].blank?
      #cookie expirations need to be in time format
      #or else they'll throw an error when they try to call .gmt on the expiration value
      #so we converte the date object to a time object
      expiration = Time.parse(Date.today.end_of_month.to_s)
      cookies[:votes] = {value: 3, :expires => expiration}
      cookies[:disabled] = {value: "", :expires => expiration}
    end

    @votes = cookies[:votes]
    @permanent = SnackData.permanent_snacks
    @suggestions = Suggestion.suggestion_data
    @disabled = deserialize_cookie(cookies[:disabled])
    @online = SnackAPI.new.online?
    
  end

  def create
    respond_to :json
    if cookies[:votes].to_i > 0 && includes_disabled?(cookies[:disabled])
                     
      cookies[:votes] = cookies[:votes].to_i - 1

      cookies[:disabled] = update_cookie_val(cookies[:disabled], params["name"])

      update_vote_count(params["name"])

      render :json => {:status => 200, return: cookies[:votes]}

    elsif cookies[:votes].to_i > 0
      render :json => { 
                      :errors => "You already voted for that" 
                      }, 
                      :status => 403

    else
      render :json => { :errors => "No votes left" }, 
                        :status => 403
    end

  end

  def includes_disabled?(cookie)
     !deserialize_cookie(cookie).include?(params["name"])
  end

  def deserialize_cookie(cookie)
    #we're using | to create the split between new items added to the cookie
    #its not elegant, but without an user login
    #there's no good way to keep track of what people have voted for
    #which is a pain, in the real world, it'd be less time intensive to just roll out devise.
   return [] if !cookie
   cookie.split("|")
  end

  def update_cookie_val(cookie, value)
      #for some reason trying to update the cookie we pass on doesn't work
      #we're probably passing the value not the reference. 
    value_array = deserialize_cookie(cookie)
    value_array << value
    value_array.join("|")
  end

  def update_vote_count(name)
      suggestion = Suggestion.where(name: name).first
      suggestion.update(votes: suggestion.votes += 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snacks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "/shared/nav" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar  navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <span class="navbar-brand" href="#">Snack Selector!</span>
    </div>

    <div class="collapse navbar-collapse navbar-right" id="navbarNav">
      <ul class="navbar-nav nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= votes_path %>">Votes </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= suggestions_path %>">Suggestions</a>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/suggestions/index.html.erb
<div class="row">
  <div class="col-sm-10">
  <% unless @online %>
    <div class="alert alert-danger">
      <strong>Warning:</strong> This page is down for mantienence.
    </div>
  <% else %>
    <div class="alert alert-notice">
      You have <strong><%= @submissions_left %></strong> suggestions left this month
    </div>


    <%= form_for :suggestion do |fr| %>
      <%= label_tag(:snack_name, "Suggest:") %>
      <%= fr.select :snack_name, @suggestions, {include_blank: true}, class: "btn btn-secondary dropdown-toggle"  %> 
      <!-- this is bad practice, would design differently for client facing -->
      <%= fr.hidden_field :location, value: "greenlake"  %>
      <%= submit_tag("Suggest", class: "btn btn-primary pull-right") %>
    <% end %>



   <br>
     <h3> Suggest a snack! </h3>
     <%= form_for :suggestion do |f| %>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label" for="snack-form">Snack:</label> 
          <div class="col-sm-10">
            <%= f.text_field :snack_name, class: "form-control", id: "snack-form", placeholder: "snack name" %>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label" for="location-form">Location:</label> 
          <div class="col-sm-10">
            <%= f.text_field :location, class: "form-control", id: "location-form", placeholder: "location" %>
          </div>
        </div>
      <%= f.submit "Suggest", class: "btn btn-primary" %>
    <% end %>

  <% end %>
  </div>
</div>

app/views/votes/index.html.erb
<div class="row">
  <% unless @online %>
    <div class="alert alert-danger">
      <strong>Warning:</strong> This page is down for mantienence.
    </div>
  <% else %>
    <div class="col-xs-4">
      <h4> Permanent Snacks</h4>
      <!-- this could be refactored into a partial, in a bigger app -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Snack Name</th>
          </tr>
        </thead>
        <tbody>
        <% @permanent.each do |item| %>
          <tr>
           <td><%= item["name"] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-xs-8">
      <h4>Suggested Snacks</h4>
      <div class="panel panel-info">
        <div class="panel-heading" id="vote-box">You have <strong id="vote-count"><%= @votes %></strong> votes left</div>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Snack Name</th>
            <th>Vote total</th>
            <th>Date Last Ordered</th>
            <th>Vote!</th>
          </tr>
        </thead>
        <tbody>
        <% @suggestions.each do |item| %>
          <tr>
            <td><%= item["name"] %></td>
            <td id=<%="#{item["name"].delete(' ')}-votes"%>><%= item["votes"] %></td>
            <td><%= item["lastPurchaseDate"] || "Never Purchased!" %></td>
            <td>
            <% unless @disabled.include?(item["name"]) %>

              <%= button_to 'Vote', {:controller => "votes", 
                                      :action => "create", 
                                      name: item["name"]},
                                      :method=> :post, 
                                      :remote => true, 
                                      class: "btn btn-primary vote-button", 
                                      id: "#{item["name"].delete(' ')}"  
              %>
              <div class="hidden" 
               id=<%="#{item["name"].delete(' ')}-hidden"%>> Already Voted</div>
            <% else %>
              Already Voted
            <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>